---
rhc_insights:
  state: present
  autoupdate: true
  remediation: absent
rhc_repositories:
  - name: 'rhel-9-for-x86_64-baseos-rpms'
    state: enabled
  - name: 'rhel-9-for-x86_64-appstream-rpms'
    state: enabled
rhc_auth:
  activation_keys:
    keys: ['employee-sku']
default_packages:
  - cockpit
enabled_services:
  - cockpit
vm_admins:
  - name: ansible
    ssh_keys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBl9C61r5gvqxZFgC+f8Lmgrl5oQ51Q2rJpQQm+KIo5T brian@addicks.us'
  - name: sysadmin
    ssh_keys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRFmPFeK5xvacd7X+IqvFKS+yKkwXpSNHv96f8zGrR4 brian@addicks.us'
vcenter_template_name: template-rhel-92