---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dynatrace_environment_url }}"
        dt_api_token: "{{ dynatrace_token }}"
        delay: 60

  rules:
    - name: Nginx unavailable
      condition: event.problemTitle contains "No process found for rule Nginx"
      action:
        run_job_template:
          name: "Linux - Webserver Setup"
          organization: "Default"
    # - name: Problem payload Dynatrace for App Failure rate increase issue
    #   condition: event.problemTitle contains "Failure rate increase"
    #   action:
    #     run_job_template:
    #       name: "Remediate Application issue"
    #       organization: "Default"
    # - name: Update comments in Dynatrace
    #   condition:
    #     all:
    #       - event.status == "OPEN"
    #   action:
    #     run_playbook:
    #       name: dt-update-comments.yml
