---
- name: Watching for Problems on Dynatrace
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dynatrace_environment_url }}"
        dt_api_token: "{{ dynatrace_token }}"
        delay: 30

  rules:
    - name: Grab event metadata to see what to key on for condition
      condition:
        all:
          - event.status == "OPEN"
      action:
        debug: