---
- name: Check Dynatrace events
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dynatrace_environment_url }}"
        dt_api_token: "{{ dynatrace_token }}"
        delay: 30

  rules:
    - name: Nginx unavailable
      condition: event.status == "OPEN" and vars.dynatrace_hosts contains event.impactedEntities[0].name
      actions:
        - debug:
        - run_job_template:
            name: "SNOW - Create Incident"
            organization: "Default"
            job_args:
              extra_vars:
                dynatrace_problem_id: "{{ event.displayId }}"
                impacted_entity: "{{ event.impactedEntities[0].name }}"
    # - name: Problem payload Dynatrace for App Failure rate increase issue
    #   condition: event.problemTitle contains "Failure rate increase"
    #   action:
    #     run_job_template:
    #       name: "Remediate Application issue"
    #       organization: "Default"
    # - name: Update comments in Dynatrace
    #   condition:
    #     all:
    #       - event.status == "OPEN"
    #   action:
    #     run_playbook:
    #       name: dt-update-comments.yml

