---
- name: "Receive logs sourced from HTTP Server Profile in PAN-OS"
  hosts: "localhost"

  ## Define how our plugin should listen for logs from PAN-OS
  sources:
    - paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5000
        type: traffic

  ## Define the conditions we are looking for. There are many types of logs
  ## in PAN-OS; we are looking just for decryption logs
  rules:
    - name: "Troubleshoot Decryption Failure"
      condition: event.meta.log_type is defined

      ## Define the action we should take should the condition be met,
      ## when we find a decryption log, which is to execute the
      ## remediation playbook
      actions:
        - debug:
        # run_playbook:
        #   name: "playbooks/decryption_remediation.yml"
