---
- name: Setup Ansible components
  hosts: aapcontroller
  gather_facts: false
  vars:
    controller_validate_certs: "{{ lookup('ansible.builtin.env', 'CONTROLLER_VALIDATE_CERTS') | ansible.builtin.bool }}"
    controller_hosts:
      - name: eda-web3
        inventory: EDA Demo Inventory
        variables:
          vm_hardware:
            num_cpus: 2
            memory_mb: 2048
          vm_nic_config:
            - type: physical
              name: eth0
              subnets:
                - type: static
                  address: 10.10.66.93/24
                  gateway: 10.10.66.1
            - type: nameserver
              address:
                - 10.10.66.20
              search:
                - addicks.us
          install_packages:
            - nginx
            - stress-ng
          firewall_services:
            - http
          enabled_services:
            - nginx
          vm_disk_size_gb: 50
    controller_groups:
      - name: webservers
        inventory: EDA Demo Inventory
        hosts:
          - eda-web1
          - eda-web2
          - eda-web3
      - name: installoneagent
        inventory: EDA Demo Inventory
        hosts:
          - eda-haproxy1
          - eda-web1
          - eda-web2
          - eda-web3

  tasks:
    - name: Update projects and inventory
      ansible.builtin.include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop:
        - hosts
        - groups
