---
- name: Enable new backend host
  hosts: haproxy
  become: true

  tasks:
    - name: Configure HAProxy
      ansible.builtin.template:
        src: ../templates/haproxy2.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - restart haproxy

  handlers:
    - name: restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
        enabled: true
