---
- name: Complete day 1 setup of RHEL hosts
  hosts: webservers

  tasks:
    - name: Include RHC role with become
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.rhc
        apply:
          become: true
      when: ansible_distribution == "RedHat"

    - name: Update all installed packages
      ansible.builtin.package:
        name: '*'
        state: latest
      become: true

    - name: Merge install_packages and default_packages variables
      ansible.builtin.set_fact:
        all_install_packages: "{{ default_packages + (install_packages | default(omit)) }}"

    - name: Install packages from install_packages and default_packages variables
      ansible.builtin.package:
        name: "{{ all_install_packages }}"
        state: present
      become: true

    - name: Install pip packages from pip_packages variable
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        state: present
      become: true
      when: pip_packages is defined

    - name: Allow services through firewall
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      become: true
      loop: "{{ firewall_services }}"
      when:
        - firewall_services is defined
        - firewall_services | length > 0

    - name: Enable services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      become: true
      loop: "{{ enabled_services }}"
      when:
        - enabled_services is defined
        - enabled_services | length > 0
...
