
---
- name: Update incident
  hosts: localhost
  connection: local
  tasks:
  - name: Update incident
    servicenow.itsm.incident:
      number: "{{ incident_record_number }}"
      state: in_progress
      other:
        comments: "Ansible is attempting Auto-Healing of {{ impacted_entity }}. \n
        See [code]<a href=\"https://{{ aap_fqdn }}#/jobs/workflow/{{ awx_workflow_job_id }}/output\" target=\"_blank\">Ansible Controller</a>[/code] for Operational Status"



