---
- name: Successfully healed ImportantApp
  hosts: localhost
  connection: local
  tasks:
  - name: Close incident
    servicenow.itsm.incident:
      number: "{{ incident_record_number }}"
      state: resolved
      close_code: "Solved Remotely (Permanently)"
      close_notes: "Closed"
      caller: "admin"
      description: "Issue has been auto-remediated, {{ impacted_entity }} is now accessible"
      short_description: "{{ impacted_entity }} is down!"
